// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD5SV-QPmye9a65RyC_2F_1aWTxEy4kv0',
    appId: '1:729308492590:web:26025ea5bbb09182fe80bf',
    messagingSenderId: '729308492590',
    projectId: 'belajar-flutter-notification',
    authDomain: 'belajar-flutter-notification.firebaseapp.com',
    storageBucket: 'belajar-flutter-notification.appspot.com',
    measurementId: 'G-V7FT5BZQLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcu3AVwPRG0lro92eqLdemjtM5CdHjmwc',
    appId: '1:729308492590:android:2c30fb267793d2effe80bf',
    messagingSenderId: '729308492590',
    projectId: 'belajar-flutter-notification',
    storageBucket: 'belajar-flutter-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQkCwcv9xCPUDhWKKCZbYh_qFe-jQs1l8',
    appId: '1:729308492590:ios:74e3145194c4f54dfe80bf',
    messagingSenderId: '729308492590',
    projectId: 'belajar-flutter-notification',
    storageBucket: 'belajar-flutter-notification.appspot.com',
    iosBundleId: 'com.example.belajarFlutterNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQkCwcv9xCPUDhWKKCZbYh_qFe-jQs1l8',
    appId: '1:729308492590:ios:74e3145194c4f54dfe80bf',
    messagingSenderId: '729308492590',
    projectId: 'belajar-flutter-notification',
    storageBucket: 'belajar-flutter-notification.appspot.com',
    iosBundleId: 'com.example.belajarFlutterNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD5SV-QPmye9a65RyC_2F_1aWTxEy4kv0',
    appId: '1:729308492590:web:e5559a4e799f0198fe80bf',
    messagingSenderId: '729308492590',
    projectId: 'belajar-flutter-notification',
    authDomain: 'belajar-flutter-notification.firebaseapp.com',
    storageBucket: 'belajar-flutter-notification.appspot.com',
    measurementId: 'G-KX2QPBWV4N',
  );
}
