// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpw8doRVQo6EYSXIgIdli0M2De15ZxOKw',
    appId: '1:480056607339:web:48b6ca0a162cdcd4f6e72e',
    messagingSenderId: '480056607339',
    projectId: 'belajar-flutter-maps',
    authDomain: 'belajar-flutter-maps.firebaseapp.com',
    storageBucket: 'belajar-flutter-maps.appspot.com',
    measurementId: 'G-7481K9BT3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6rXdDtqulVoF5itBv9YFxoTw89m667xQ',
    appId: '1:480056607339:android:1a420f9323fed439f6e72e',
    messagingSenderId: '480056607339',
    projectId: 'belajar-flutter-maps',
    storageBucket: 'belajar-flutter-maps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4B5rO2zwxBipQAOOfTq5Tr1MqO1jPdn4',
    appId: '1:480056607339:ios:bf4682ae811b884df6e72e',
    messagingSenderId: '480056607339',
    projectId: 'belajar-flutter-maps',
    storageBucket: 'belajar-flutter-maps.appspot.com',
    iosBundleId: 'com.example.belajarFlutterMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4B5rO2zwxBipQAOOfTq5Tr1MqO1jPdn4',
    appId: '1:480056607339:ios:bf4682ae811b884df6e72e',
    messagingSenderId: '480056607339',
    projectId: 'belajar-flutter-maps',
    storageBucket: 'belajar-flutter-maps.appspot.com',
    iosBundleId: 'com.example.belajarFlutterMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpw8doRVQo6EYSXIgIdli0M2De15ZxOKw',
    appId: '1:480056607339:web:9a6f1fd139b683fff6e72e',
    messagingSenderId: '480056607339',
    projectId: 'belajar-flutter-maps',
    authDomain: 'belajar-flutter-maps.firebaseapp.com',
    storageBucket: 'belajar-flutter-maps.appspot.com',
    measurementId: 'G-YEJNPZSSYW',
  );
}
