// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAi1b-nSU93bVo3ABmGGPYUqiLiyUKtCw',
    appId: '1:551190969707:web:893ce81381619fc0ca202e',
    messagingSenderId: '551190969707',
    projectId: 'belajar-flutter-authentication',
    authDomain: 'belajar-flutter-authentication.firebaseapp.com',
    storageBucket: 'belajar-flutter-authentication.appspot.com',
    measurementId: 'G-E1Z392LZQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt4kGt6xURcZGtXOyzcSWTAQ_K4MS2D2c',
    appId: '1:551190969707:android:1205d54d28345ea2ca202e',
    messagingSenderId: '551190969707',
    projectId: 'belajar-flutter-authentication',
    storageBucket: 'belajar-flutter-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEm4CzlO1p4gV7eHcBz2v8W5B2U1HAcCk',
    appId: '1:551190969707:ios:8f69633ad3fcbc37ca202e',
    messagingSenderId: '551190969707',
    projectId: 'belajar-flutter-authentication',
    storageBucket: 'belajar-flutter-authentication.appspot.com',
    iosBundleId: 'com.example.belajarFlutterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEm4CzlO1p4gV7eHcBz2v8W5B2U1HAcCk',
    appId: '1:551190969707:ios:8f69633ad3fcbc37ca202e',
    messagingSenderId: '551190969707',
    projectId: 'belajar-flutter-authentication',
    storageBucket: 'belajar-flutter-authentication.appspot.com',
    iosBundleId: 'com.example.belajarFlutterAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAi1b-nSU93bVo3ABmGGPYUqiLiyUKtCw',
    appId: '1:551190969707:web:8248f90edbc486f0ca202e',
    messagingSenderId: '551190969707',
    projectId: 'belajar-flutter-authentication',
    authDomain: 'belajar-flutter-authentication.firebaseapp.com',
    storageBucket: 'belajar-flutter-authentication.appspot.com',
    measurementId: 'G-8WBRG523G9',
  );
}
